language: ruby
sudo: false
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - 2.4.1
  - jruby-9.1.8.0
script: rake test

branches:
  only:
    - master
    - /stable$/

notifications:
  slack:
    secure: XubYKuE3+6VJNDvjgVE2P0cp3Km/We1RlhkeHBGI+r0wYqAg6tab33IYFo+3BgE0xwl1RX3SwX1pbPt3LVDi8zLA5mkmmmDiNIqqYa1vICDgRgu8OTCRcCCTaWB5DhVY11iZaYFyQEoQ+aUHp9QoYeH7Qmp+M2//+DYG9wka6kA=
